-- OPTIONAL. Ported from RaahSaathi_FINAL. NOT applied by `npm run db:push` and NOT read by the
-- current Smart Route code (it reads safety_zones and sos_events). Kept for future persistence.
-- Optional migration. Existing safety_zones/SOS tables are intentionally not replaced.
-- These tables contain only operational/aggregated data needed by the feature.

create table if not exists public.safety_heatmap_cells (
  id bigint generated by default as identity primary key,
  cell_key text not null,
  centroid_lat double precision not null check (centroid_lat between -90 and 90),
  centroid_lng double precision not null check (centroid_lng between -180 and 180),
  lighting_score smallint check (lighting_score between 0 and 100),
  crowd_score smallint check (crowd_score between 0 and 100),
  incident_count integer not null default 0 check (incident_count >= 0),
  congestion_ratio numeric(5,4) check (congestion_ratio between 0 and 1),
  sample_count integer not null default 0 check (sample_count >= 0),
  observed_at timestamptz not null default now(),
  unique(cell_key, observed_at)
);

create index if not exists safety_heatmap_cells_cell_idx on public.safety_heatmap_cells(cell_key);
create index if not exists safety_heatmap_cells_observed_idx on public.safety_heatmap_cells(observed_at desc);

create table if not exists public.route_events (
  id bigint generated by default as identity primary key,
  booking_id text,
  event_type text not null check (event_type in ('optimized','reroute_proposed','reroute_confirmed','reroute_declined')),
  provider text,
  previous_eta_sec integer,
  new_eta_sec integer,
  previous_safety_score smallint,
  new_safety_score smallint,
  reason text,
  created_at timestamptz not null default now()
);
create index if not exists route_events_booking_idx on public.route_events(booking_id, created_at desc);

create table if not exists public.carpool_requests (
  id uuid primary key default gen_random_uuid(),
  booking_id text not null,
  matched_booking_id text not null,
  status text not null default 'pending_confirmation' check (status in ('pending_confirmation','confirmed','declined','expired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists carpool_requests_booking_idx on public.carpool_requests(booking_id, created_at desc);

create table if not exists public.traffic_snapshots (
  id bigint generated by default as identity primary key,
  centroid_lat double precision not null,
  centroid_lng double precision not null,
  current_speed_kmh numeric,
  free_flow_speed_kmh numeric,
  congestion_ratio numeric(5,4),
  confidence numeric,
  observed_at timestamptz not null default now()
);
create index if not exists traffic_snapshots_observed_idx on public.traffic_snapshots(observed_at desc);

-- RLS: browser clients may read only aggregated heatmap data. Operational writes stay server-side.
alter table public.safety_heatmap_cells enable row level security;
alter table public.route_events enable row level security;
alter table public.carpool_requests enable row level security;
alter table public.traffic_snapshots enable row level security;

drop policy if exists "authenticated_read_heatmap" on public.safety_heatmap_cells;
create policy "authenticated_read_heatmap" on public.safety_heatmap_cells for select to authenticated using (true);

drop policy if exists "authenticated_read_traffic" on public.traffic_snapshots;
create policy "authenticated_read_traffic" on public.traffic_snapshots for select to authenticated using (true);

-- route_events and carpool_requests are intentionally not browser-readable by default.
-- Add project-specific policies only after mapping your existing auth/role model.

-- Sustainability events / leaderboard support. Store verified completed-trip events in production.
create table if not exists public.sustainability_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  booking_id text,
  route_distance_saved_km numeric(8,3) not null default 0,
  carpool_vehicle_trips_avoided integer not null default 0,
  co2_saved_grams numeric(12,2) not null default 0,
  points integer not null default 0,
  source text not null default 'prototype',
  created_at timestamptz not null default now()
);
create index if not exists sustainability_events_user_idx on public.sustainability_events(user_id, created_at desc);

alter table public.sustainability_events enable row level security;
-- Production policy should be mapped to the existing authenticated user/role model.
